macos_min_version:
  - 10.9
macos_machine:
  - x86_64-apple-darwin13.4.0
MACOSX_DEPLOYMENT_TARGET:
  - 10.9
CONDA_BUILD_SYSROOT:            # [osx]
  - /opt/MacOSX10.9.sdk         # [osx]
# This helps CMAKE find the sysroot. See
# https://cmake.org/cmake/help/v3.11/variable/CMAKE_OSX_SYSROOT.html
SDKROOT:                        # [osx]
  - /opt/MacOSX10.9.sdk         # [osx]
# makes autotools verbose
VERBOSE_AT:
  - V=1
# makes cmake verbose
VERBOSE_CM:
  - VERBOSE=1

## the dependencies that we build against multiple versions
python:
  - 2.7

# The build time only dependencies (build requirements).
# Updating these to the latest version all the time is OK and a good idea.
# These versions should match the versions inside bob-devel as well (if they
# overlap) so update them in both places.
cmake:
  - 2.8.10.2
pkg_config:
  - 0.29.2

# The dependencies that we link against (host requirements).
# Ideally we want to build against the oldest possible version of packages when
# we are linking against them. It is best to keep this in sync with:
# https://github.com/AnacondaRecipes/aggregate/blob/master/conda_build_config.yaml
numpy:
  - 1.11.3
boost:
  - 1.57.0
ffmpeg:
  - 2.8.10
fftw:
  - 3.3.8
giflib:
  - 5.1.4
hdf5:
  - 1.8.17
jpeg:
  - 8d
libblitz:
  - 1.0.1
libmatio:
  - 1.5.6
libpng:
  - 1.6.36
libsvm:
  - 3.22
libtiff:
  - 4.0.6
nose:
  - 1.3.7
openblas:
  - 0.3.3
sqlite:
  - 3.7.13
vlfeat:
  - 0.9.21
xz:
  - 5.2.4
zlib:
  - 1.2.11

# The dependencies that are needed for runtime only (run requirements).
# These versions **should** match the versions inside bob-devel recipe.
matplotlib:
  - 1.5.1
pillow:
  - 3.4.2
scipy:
  - 1.2.1
setuptools:
  - 41.0.0
sphinx:
  - 1.8.5
sqlalchemy:
  - 1.3.1
