# The main copy of this list is in bob-devel. Keep them synced please.
{% set nopin = ['ca-certificates', 'certifi', 'openssl', 'libstdcxx-ng', 'libgcc-ng', 'libgfortran-ng', 'libcxx', 'libcxxabi', 'libgfortran'] %}
{% set name = 'bob' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  ignore_run_exports:
  {% for package in resolved_packages('host') %}
    - {{ package.split()[0] }}
  {% endfor %}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    # the list below contains all public packages. This is/should be the same
    # list as order.txt (save for private packages) in bob.nightlies.

    # Do not remove the tag below which is used for automatic parsing of this recipe
    # LIST OF BOB PACKAGES - START
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.math
    - bob.measure
    - bob.io.image
    - bob.db.base
    - bob.io.video
    - bob.io.audio
    - bob.sp
    - bob.ap
    - bob.ip.base
    - bob.ip.color
    - bob.ip.gabor
    - bob.learn.activation
    - bob.learn.linear
    - bob.db.iris
    - bob.learn.em
    - bob.db.mnist
    - bob.db.atnt
    - bob.ip.facedetect
    - gridtk
    - bob.pipelines
    - bob.learn.tensorflow  # [linux]
    - bob.bio.base
    - bob.bio.gmm
    - bob.bio.face
    - bob.bio.video
    - bob.bio.vein
    - bob.ip.qualitymeasure
    - bob.pad.base
    - bob.pad.face
    - bob.fusion.base
    - bob.ip.binseg
    - bob.io.stream
    - bob.ip.stereo
    # LIST OF BOB PACKAGES - END
  run:
    - python
    - setuptools
  run_constrained:
  {% for package in resolved_packages('host') %}
  {% if package.split()[0] not in nopin %}
    - {{ package }}
  {% endif %}
  {% endfor %}

test:
  imports:
    - {{ name }}
  commands:
    - export SDKROOT="{{ SDKROOT }}"  # [osx]
    - export MACOSX_DEPLOYMENT_TARGET="{{ MACOSX_DEPLOYMENT_TARGET }}"  # [osx]
    # skip the boundary_grouping test from bob.fusion.base because somehow this test fails here due to matplotlib's backend.
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --pyargs {{ name }} -k "not boundary_grouping"
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - sphinxcontrib-programoutput {{ sphinxcontrib_programoutput }}
    - graphviz {{ graphviz }}
    - font-ttf-dejavu-sans-mono {{ font_ttf_dejavu_sans_mono }}
    - cmake {{ cmake }}
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - pkg-config {{ pkg_config }}
    - freetype {{ freetype }}
    - psutil {{ psutil }}
    - dask-ml {{ dask_ml }}
    - make {{ make }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bob is a free signal-processing and machine learning toolbox originally developed by the Biometrics group at Idiap Research Institute, in Switzerland.
  license_family: BSD
  doc_url: https://www.idiap.ch/software/bob/documentation
  dev_url: https://gitlab.idiap.ch/bob/bob
