{% set name = 'bob' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  ignore_run_exports:
  {% for package in resolved_packages('host') %}
    - {{ package.split()[0] }}
  {% endfor %}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob-devel {{ bob_devel }}
    # the list below contains all public packages. This is/should be the same
    # list as order.txt (save for private packages) in bob.nightlies.
    - bob.buildout
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.math
    - bob.measure
    - bob.io.image
    - bob.db.base
    - bob.io.video
    - bob.io.matlab
    - bob.io.audio
    - bob.sp
    - bob.ap
    - bob.ip.base
    - bob.ip.color
    - bob.ip.draw
    - bob.ip.gabor
    - bob.learn.activation
    - bob.learn.libsvm
    - bob.learn.linear
    - bob.learn.mlp
    - bob.learn.boosting
    - bob.db.iris
    - bob.learn.em
    - bob.db.wine
    - bob.db.mnist
    - bob.db.atnt
    - bob.ip.facedetect
    - bob.ip.optflow.hornschunck
    - bob.ip.optflow.liu
    - bob.ip.flandmark
    - gridtk
    - bob.ip.qualitymeasure
    - bob.ip.skincolorfilter
    - bob.db.arface
    - bob.db.asvspoof
    - bob.db.asvspoof2017
    - bob.db.atvskeystroke
    - bob.db.avspoof
    - bob.db.banca
    - bob.db.biosecure
    - bob.db.biosecurid.face
    - bob.db.casme2
    - bob.db.caspeal
    - bob.db.cohface
    - bob.db.frgc
    - bob.db.gbu
    - bob.db.hci_tagging
    - bob.db.ijbc
    - bob.db.kboc16
    - bob.db.lfw
    - bob.db.livdet2013
    - bob.db.mobio
    - bob.db.msu_mfsd_mod
    - bob.db.multipie
    - bob.db.nist_sre12
    - bob.db.putvein
    - bob.db.replay
    - bob.db.replaymobile
    - bob.db.scface
    - bob.db.utfvp
    - bob.db.verafinger
    - bob.db.fv3d
    - bob.db.voicepa
    - bob.db.xm2vts
    - bob.db.youtube
    - bob.db.pericrosseye
    - bob.db.maskattack
    - bob.bio.base
    - bob.bio.gmm
    - bob.bio.face
    - bob.bio.spear
    - bob.bio.video
    - bob.bio.vein
    - bob.db.voxforge
    - bob.db.ijba
    - bob.rppg.base
    - bob.pad.base
    - bob.pad.face
    - bob.pad.voice
    - bob.pad.vein
    - bob.db.oulunpu
    - bob.db.uvad
    - bob.db.cuhk_cufs
    - bob.db.cbsr_nir_vis_2
    - bob.db.nivl
    - bob.db.pola_thermal
    - bob.db.cuhk_cufsf
    - bob.ip.mtcnn  # [linux]
    - bob.ip.tensorflow_extractor  # [linux]
    - bob.ip.caffe_extractor  # [linux]
    - bob.bio.caffe_face  # [linux]
    - bob.fusion.base
  run:
    - python
    - setuptools
  run_constrained:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
    # fix for the CONDA_BUILD_SYSROOT variable missing at test time
    - export CONDA_BUILD_SYSROOT={{ CONDA_BUILD_SYSROOT }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - cmake
    - pkg-config
    - freetype
    - psutil  # for bob.io.video
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bob is a free signal-processing and machine learning toolbox originally developed by the Biometrics group at Idiap Research Institute, in Switzerland.
  license_family: BSD
  doc_url: https://www.idiap.ch/software/bob/documentation
  dev_url: https://gitlab.idiap.ch/bob/bob
