{% set name = "bob" %}
{% set build_type = "Release" %}
{% set python_version = "2.7" %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  script:
    - cmake -DCMAKE_BUILD_TYPE={{ build_type }} -DCMAKE_PREFIX_PATH=${PREFIX} -DCMAKE_INSTALL_PREFIX=${PREFIX} -DBOOST_ROOT=${PREFIX} -DPYTHON_VERSION={{ python_version }} -DBOB_VERSION={{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }} -DWITH_QT4=OFF {{ environ.get('RECIPE_DIR') + '/..' }}
    - make VERBOSE=1 all
    - make VERBOSE=1 test
    - make VERBOSE=1 install
    - cd {{ environ.get('RECIPE_DIR') + '/../python' }}
    - PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${PREFIX}/lib/pkgconfig python setup.py build --build-base=${SRC_DIR}/build install --single-version-externally-managed --record ${SRC_DIR}/record.txt
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst ../COPYING doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - pkg-config {{ pkg_config }}

  host:
    - boost {{ boost }}
    - ffmpeg {{ ffmpeg }}
    - fftw {{ fftw }}
    - giflib {{ giflib }}
    - hdf5 {{ hdf5 }}
    - jpeg {{ jpeg }}
    - libblitz {{ libblitz }}
    - libmatio {{ libmatio }}
    - libpng {{ libpng }}
    - libsvm {{ libsvm }}
    - libtiff {{ libtiff }}
    - matplotlib {{ matplotlib }}
    - nose {{ nose }}
    - numpy {{ numpy }}
    - openblas {{ openblas }}
    - pillow {{ pillow }}
    - python {{ python_version }}
    - scipy {{ scipy }}
    - setuptools {{ setuptools }}
    - sphinx {{ sphinx }}
    - sqlalchemy {{ sqlalchemy }}
    - sqlite {{ sqlite }}
    - vlfeat {{ vlfeat }}

  run:
    - boost {{ boost }}.*
    - ffmpeg {{ ffmpeg }}.*
    - fftw {{ fftw }}.*
    - giflib {{ giflib }}.*
    - hdf5 {{ hdf5 }}.*
    - jpeg {{ jpeg }}.*
    - libblitz {{ libblitz }}.*
    - libmatio {{ libmatio }}.*
    - libpng {{ libpng }}.*
    - libsvm {{ libsvm }}.*
    - libtiff {{ libtiff }}.*
    - matplotlib
    - nose
    - {{ pin_compatible('numpy') }}
    - openblas {{ openblas }}.*
    - pillow
    - python {{ python_version }}.*
    - scipy
    - setuptools
    - sphinx {{ sphinx }}.*
    - sqlalchemy
    - sqlite {{ sqlite }}.*
    - vlfeat {{ vlfeat }}.*

test:
  requires:
    - nose
    - coverage
    - sphinx_rtd_theme

  imports:
    - bob

  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build ${PREFIX}/share/doc/{{ name }}/doc sphinx
    - if [ -n "${CI_PROJECT_DIR}" ]; then mv sphinx "${CI_PROJECT_DIR}/"; fi
    - sphinx-build -b doctest ${PREFIX}/share/doc/{{ name }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://www.idiap.ch/software/bob
  summary: Bob is a free signal-processing and machine learning toolbox
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL
  license_file: ../COPYING

extra:
  recipe-maintainers:
    - anjos
