# The main copy of this list is in bob-devel. Keep them synced please.
{% set nopin = ['ca-certificates', 'certifi', 'openssl', 'libstdcxx-ng', 'libgcc-ng', 'libcxx', 'libcxxabi'] %}
{% set name = 'bob' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  ignore_run_exports:
  {% for package in resolved_packages('host') %}
    - {{ package.split()[0] }}
  {% endfor %}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob-devel {{ bob_devel }}
    # the list below contains all public packages. This is/should be the same
    # list as order.txt (save for private packages) in bob.nightlies.

    # Do not remove the tag below which is used for automatic parsing of this recipe
    # LIST OF BOB PACKAGES - START
    - bob.buildout ==2.3.0
    - bob.extension ==6.0.0
    - bob.blitz ==2.0.23
    - bob.core ==2.2.7
    - bob.io.base ==3.0.10
    - bob.math ==3.1.8
    - bob.measure ==4.2.3
    - bob.io.image ==2.5.0
    - bob.db.base ==3.1.0
    - bob.io.video ==3.0.4
    - bob.io.audio ==2.0.14
    - bob.sp ==2.0.17
    - bob.ap ==2.1.12
    - bob.ip.base ==2.2.7
    - bob.ip.color ==2.0.17
    - bob.ip.gabor ==2.0.18
    - bob.learn.activation ==2.0.17
    - bob.learn.linear ==2.1.9
    - bob.learn.libsvm ==2.1.6
    - bob.learn.mlp ==2.1.13
    - bob.db.iris ==2.1.8
    - bob.learn.em ==2.1.7
    - bob.db.mnist ==2.2.7
    - bob.db.atnt ==2.0.17
    - bob.ip.facedetect ==4.0.0
    - gridtk ==1.8.2
    - bob.ip.qualitymeasure ==1.1.7
    - bob.pipelines ==1.0.0
    - bob.learn.tensorflow ==2.0.0  # [linux]
    - bob.bio.base ==5.0.0
    - bob.bio.gmm ==4.0.0
    - bob.bio.face ==5.0.0
    - bob.bio.video ==4.0.0
    - bob.bio.vein ==2.0.0
    - bob.pad.base ==3.0.0
    - bob.pad.face ==3.0.0
    - bob.fusion.base ==0.0.6
    - bob.learn.pytorch ==0.2.0  # [linux]
    - bob.ip.binseg ==1.2.0  # [linux]
    # LIST OF BOB PACKAGES - END
  run:
    - python
    - setuptools
  run_constrained:
  {% for package in resolved_packages('host') %}
  {% if package.split()[0] not in nopin %}
    - {{ package }}
  {% endif %}
  {% endfor %}

test:
  imports:
    - {{ name }}
  commands:
    - export SDKROOT="{{ SDKROOT }}"  # [osx]
    - export MACOSX_DEPLOYMENT_TARGET="{{ MACOSX_DEPLOYMENT_TARGET }}"  # [osx]
    # skip the boundary_grouping test from bob.fusion.base because somehow this test fails here due to matplotlib's backend.
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --pyargs {{ name }} -k "not boundary_grouping"
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - cmake
    - pytest
    - pkg-config
    - freetype
    - psutil  # for bob.io.video
    - dask-ml
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bob is a free signal-processing and machine learning toolbox originally developed by the Biometrics group at Idiap Research Institute, in Switzerland.
  license_family: BSD
  doc_url: https://www.idiap.ch/software/bob/documentation
  dev_url: https://gitlab.idiap.ch/bob/bob
