{% set name = 'bob' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  ignore_run_exports:
  {% for package in resolved_packages('host') %}
    - {{ package.split()[0] }}
  {% endfor %}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob-devel {{ bob_devel }}
    # the list below contains all public packages. This is/should be the same
    # list as order.txt (save for private packages) in bob.nightlies.
    - bob.buildout 2.1.6
    - bob.extension 2.5.0
    - bob.blitz 2.0.15
    - bob.core 2.2.0
    - bob.io.base 3.0.3
    - bob.math 3.1.1
    - bob.measure 3.0.0
    - bob.io.image 2.4.1
    - bob.db.base 3.0.0
    - bob.io.video 2.1.1
    - bob.io.matlab 2.0.11
    - bob.io.audio 2.0.7
    - bob.sp 2.0.11
    - bob.ap 2.1.6
    - bob.ip.base 2.2.1
    - bob.ip.color 2.0.11
    - bob.ip.draw 2.0.10
    - bob.ip.gabor 2.0.12
    - bob.learn.activation 2.0.11
    - bob.learn.libsvm 2.1.0
    - bob.learn.linear 2.1.3
    - bob.learn.mlp 2.1.7
    - bob.learn.boosting 2.0.14
    - bob.db.iris 2.1.2
    - bob.learn.em 2.1.1
    - bob.db.wine 2.0.10
    - bob.db.mnist 2.2.0
    - bob.db.atnt 2.0.11
    - bob.ip.facedetect 2.1.5
    - bob.ip.optflow.hornschunck 2.0.14
    - bob.ip.optflow.liu 2.0.13
    - bob.ip.flandmark 2.1.7
    - gridtk 1.6.1
    - bob.ip.qualitymeasure 1.1.0
    - bob.ip.skincolorfilter 0.0.4
    - bob.ip.facelandmarks 1.0.5
    - bob.ip.dlib 1.0.4
    - bob.db.arface 2.1.5
    - bob.db.asvspoof 1.2.0
    - bob.db.asvspoof2017 1.1.0
    - bob.db.atvskeystroke 2.1.6
    - bob.db.avspoof 2.3.0
    - bob.db.banca 2.1.6
    - bob.db.biosecure 2.1.6
    - bob.db.biosecurid.face 2.1.9
    - bob.db.casme2 2.1.6
    - bob.db.caspeal 2.1.6
    - bob.db.cohface 1.1.0
    - bob.db.frgc 2.1.4
    - bob.db.gbu 2.1.5
    - bob.db.hci_tagging 1.1.0
    - bob.db.ijba 2.1.0
    - bob.db.kboc16 2.1.0
    - bob.db.lfw 2.1.6
    - bob.db.livdet2013 2.1.0
    - bob.db.mobio 2.2.0
    - bob.db.msu_mfsd_mod 2.2.4
    - bob.db.multipie 2.1.5
    - bob.db.nist_sre12 3.0.4
    - bob.db.putvein 1.3.0
    - bob.db.replay 3.0.4
    - bob.db.replaymobile 1.1.4
    - bob.db.scface 2.1.6
    - bob.db.utfvp 3.0.0
    - bob.db.verafinger 2.0.1
    - bob.db.fv3d 1.1.1
    - bob.db.voicepa 1.1.0
    - bob.db.xm2vts 2.1.5
    - bob.db.youtube 2.1.5
    - bob.db.pericrosseye 1.0.2
    - bob.db.cuhk_cufs 2.2.0
    - bob.bio.base 3.3.0
    - bob.bio.gmm 3.2.1
    - bob.bio.face 3.4.0
    - bob.bio.spear 3.2.0
    - bob.bio.video 3.4.1
    - bob.bio.vein 1.1.0
    - bob.db.voxforge 2.3.1
    - bob.pad.base 2.0.0
    - bob.pad.face 2.0.1
    - bob.pad.vein 1.0.0
  run:
    - python
    - setuptools
  run_constrained:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - cmake
    - pkg-config
    - freetype
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bob is a free signal-processing and machine learning toolbox originally developed by the Biometrics group at Idiap Research Institute, in Switzerland.
  license_family: BSD
  doc_url: https://www.idiap.ch/software/bob/documentation
  dev_url: https://gitlab.idiap.ch/bob/bob
