{% set name = "bob" %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: 0
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${PREFIX} -DPYTHON_VERSION=2.7 -DBOB_VERSION={{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }} -DWITH_QT4=OFF {{ environ.get('RECIPE_DIR') + '/..' }}
    - make VERBOSE=1 all
    - make VERBOSE=1 test
    - make VERBOSE=1 nosetests
    - make VERBOSE=1 sphinx-doctest
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - pkg-config {{ pkg_config }}

  host:
    - python 2.7
    - setuptools {{ setuptools }}
    - sqlite {{ sqlite }}
    - sqlalchemy {{ sqlalchemy }}
    - ffmpeg {{ ffmpeg }}
    - libblitz {{ libblitz }}
    - boost {{ boost }}
    - jpeg {{ jpeg }}
    - giflib {{ giflib }}
    - libtiff {{ libtiff }}
    - libmatio {{ libmatio }}
    - libpng {{ libpng }}
    - vlfeat {{ vlfeat }}
    - libsvm {{ libsvm }}
    - hdf5 {{ hdf5 }}
    - sphinx {{ sphinx }}
    - nose {{ nose }}
    - pillow {{ pillow }}
    - numpy {{ numpy }}
    - scipy {{ scipy }}
    - matplotlib {{ matplotlib }}
    - fftw {{ fftw }}
    - openblas {{ openblas }}

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - sqlalchemy
    - pillow
    - matplotlib

test:
  imports:
    - bob

  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
    - python -c "import bob; print bob.version"

about:
  home: https://gitlab.idiap.ch/bob/bob
  summary: Bob is a free signal-processing and machine learning toolbox
  license: GNU General Public License v3 (GPLv3)
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - anjos
